version: '3.9'
services:
  notebook:
    container_name: langchain
    image: jupyter/datascience-notebook
    ports:
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/langchain/:/home/jovyan/langchain/
    command: start-notebook.sh --NotebookApp.token=''