version: '3.9'
services:
  langchain:
    container_name: langchain
    image: jupyter/datascience-notebook
    ports:
      - '8000:8000'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/langchain/:/home/langchain/
    command: start-notebook.sh --NotebookApp.token=''